* Ordering-System for the SoLaWi-Rhein-Neckar
** Installation
*** Make sure you have "virtualenv" installed
#+BEGIN_SRC shell
$ virtualenv --version
#+END_SRC

*** Clone this repo and move into subdirectory
#+BEGIN_SRC shell
$ git clone git@github.com:mrtukkin/solawi.git
$ cd solawi
#+END_SRC

*** Initialize the virtual environment and install dependencies
#+BEGIN_SRC shell
solawi $ virtualenv -p python3 venv
solawi $ source venv/bin/activate
(venv) solawi $ pip3 install django
#+END_SRC

*** Start the app
If you run the app for the first time, make sure you create a super-user:

#+BEGIN_SRC shell
(venv) solawi $ ./manage.py createsuperuser
#+END_SRC

Start the app with:

#+BEGIN_SRC shell
(venv) solawi $ ./manage.py runserver
#+END_SRC

** Usage
There are not many views yet, but you can create data objects in the admin view.
Go to http://127.0.0.1:8000/admin and login with your super-user.
Ther is no DataBase in this Repo. Therefore you wont be able to check most of the views till you add some Data through your admin login.

** Data Model
For the Data Model look into MODELL.md

Ich fange mal an, das Datenbank-Diagramm in draw.io nachzuzeichnen, das Merlin &Co derzeit verwenden, dann haben wir eine Diskussions-Grundlage.

Damit wir die Diagramme up-to-date halten können, habe ich zwei automatische Ansätze getestet: 

Django bietet einen Export zu "Graphviz" an (Dateiendung .dot), Anleitung: https://django-extensions.readthedocs.io/en/latest/installation_instructions.html
 Draw.io kann das leider nur als Bild importieren, aber möglicherweise finden wir ein anderes Programm mit dem wir graphviz Datein weiterbearbeiten können.

- Ansehen (alle): https://www.draw.io/#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Fregenduft%2Fbestellsystem%2Fdevelopment%2Fsolawi_bestellsystem_database_imported.drawio
- Bearbeiten (nachdem ich euren github-usernamen freigeschaltet habe!): https://www.draw.io/#Hregenduft%2Fbestellsystem%2Fdevelopment%2Fsolawi_bestellsystem_database_imported.drawio

Und natürlich kann man Sqlite exportieren (sqlite3 db.sqlite3 .schema > schema.sql, danach pretty-print http://www.dpriver.com/pp/sqlformat.htm danach draw.io -> Arrange -> Insert SQL)
- Ansehen (alle): https://www.draw.io/#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Fregenduft%2Fbestellsystem%2Fdevelopment%2Fsolawi_bestellsystem_database.drawio

- Bearbeiten (nachdem ich euren github-usernamen freigeschaltet habe!): https://www.draw.io/#Hregenduft%2Fbestellsystem%2Fdevelopment%2Fsolawi_bestellsystem_database.drawio

NEUER Vorschlag von Regenduft (einfacher dank nun offiziellem Punktesystem):

- Ansehen (alle): https://www.draw.io/#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Fregenduft%2Fbestellsystem%2Fdevelopment%2Fsolawi_bestellsystem_database_neu.drawio

- Bearbeiten (nachdem ich eueren github-usernamen freigeschaltet habe!): https://www.draw.io/#Hregenduft%2Fbestellsystem%2Fdevelopment%2Fsolawi_bestellsystem_database_neu.drawio


