# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 21:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_member', models.BooleanField(default=True, verbose_name='Make a paying member')),
                ('is_supervisor', models.BooleanField(default=False, verbose_name='Make a depot supervisor')),
                ('countshares', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('assets', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'packed product',
                'verbose_name_plural': 'packed products',
            },
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'content of order',
                'verbose_name_plural': 'content of orders',
            },
        ),
        migrations.CreateModel(
            name='DefaultBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='defaultbaskets', to='solawi.OrderContent')),
                ('name', models.CharField(default='', help_text='basket name', max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'default orderbasket',
                'verbose_name_plural': 'default orderbaskets',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': 'depot',
                'verbose_name_plural': 'depots',
            },
        ),
        migrations.CreateModel(
            name='OrderBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='order', to='solawi.OrderContent')),
                ('isoweek', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('isoyear', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(2018)])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderbaskets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ordering basket',
                'verbose_name_plural': 'ordering baskets',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('orderable', models.BooleanField(default=True)),
                ('unit', models.CharField(default='', help_text='measuring unit,e.g. kg or L', max_length=15)),
                ('module_time', models.IntegerField(blank=True, help_text='module duration in weeks', null=True)),
                ('price_of_module', models.FloatField(blank=True, help_text='modular product price', null=True)),
                ('exchange_value', models.FloatField(default=0, help_text='exchange value per unit', null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderable', models.BooleanField(default=True)),
                ('packagesize', models.FloatField(default=1)),
                ('producttype', models.CharField(blank=True, default='', help_text='product type', max_length=15)),
                ('max_at_once', models.IntegerField(default=5, help_text='max amount orderable at once')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='solawi.Product')),
            ],
            options={
                'verbose_name': 'properties of product',
                'verbose_name_plural': 'properties of products',
            },
        ),
        migrations.CreateModel(
            name='RegularyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('period', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('lastorder_isoweek', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('lastorder_isoyear', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(2018)])),
                ('lastaccses', models.DateField(auto_now=True)),
                ('productproperty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solawi.ProductProperty')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regularyorders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'regularly order',
                'verbose_name_plural': 'regularly orders',
            },
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='productproperties',
            field=models.ManyToManyField(related_name='isin', through='solawi.Amount', to='solawi.ProductProperty'),
        ),
        migrations.AddField(
            model_name='amount',
            name='ordercontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='solawi.OrderContent'),
        ),
        migrations.AddField(
            model_name='amount',
            name='productproperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amount', to='solawi.ProductProperty'),
        ),
        migrations.AddField(
            model_name='user',
            name='defaultbasket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='solawi.DefaultBasket'),
        ),
        migrations.AddField(
            model_name='user',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='solawi.Depot'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='regularyorder',
            unique_together=set([('user', 'productproperty')]),
        ),
        migrations.AlterUniqueTogether(
            name='productproperty',
            unique_together=set([('product', 'producttype', 'packagesize')]),
        ),
        migrations.AlterUniqueTogether(
            name='orderbasket',
            unique_together=set([('isoweek', 'isoyear', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='amount',
            unique_together=set([('ordercontent', 'productproperty')]),
        ),
    ]
